---
title: '2019-03-27'
author: "LKS"
date: "2019年3月27日"
output: html_document
---
```{r}
Sys.timezone()
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```

```{r}
dtObject
```

```{r}
library(lubridate)
Sys.timezone()
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
LisbonDateTime <- with_tz(twDateTime, tz="Europe/Lisbon")
LisbonDateTime

typeof(twDateTime)
as.integer(twDateTime)
as.double(twDateTime)
typeof(LisbonDateTime)
as.integer(LisbonDateTime)
as.double(LisbonDateTime)

NowDateTime <- dmy_hm("27-03-2019 16:04")
TwDateTime <- dmy_hm("27-03-2019 16:04", tz="Asia/Taipei")

TwDateTime

currenttime <- dmy_hm("27-03-2019 16:04")

currenttime

timeone <- ymd("2018-09-11")
timeone

timetwo <- mdy("March 3, 2019")
timetwo

as.double(timeone)
as.double(timetwo)
as.double(currenttime)
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)

a+b
class(a+b)
aaL <- a+aL
aL+bL
class(aL+bL)

class(aL*bL)
class(aL/bL)

a+5
a-5
a*5
a/5

```

```{r}
startingDate <- ymd("2000-02-02")

startingDate + years(1)
startingDate + dyears(1)
```

```{r}
x <- 5
y <- 7

x2 <- c(1,5,10)
y2 <- c(-1,5,20)

x >= y
x == y
x < y
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")

x2 ==y2
```

